version: '3.9'

services:
  pydb:
    container_name: pydb
    image: postgres:latest
    ports:
      - 5050:5432
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U <nome_do_user> -d <nome_do_database>"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s
    # volumes:
      # - komercio:/var/lib/postgresql/data:rw

# volumes:
#   komercio:
#     external: true
